<a href="https://colab.research.google.com/github/lakshaygoyal425/Pytorch/blob/master/Pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from __future__ import print_function
import torch

In [3]:
x = torch.empty(5,3)
print(x)

tensor([[4.7794e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 0.0000e+00, 0.0000e+00]])


In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.9237, 0.7377, 0.0812],
        [0.5629, 0.2743, 0.2362],
        [0.9565, 0.9275, 0.9916],
        [0.3160, 0.3572, 0.9022],
        [0.7796, 0.2045, 0.3159]])


In [5]:
x = torch.ones(5,3 , dtype=torch.long)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


In [6]:
x = torch.tensor([5.3,4])
print(x)

tensor([5.3000, 4.0000])


In [9]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)

x = torch.randn_like(x , dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.5203,  0.4406, -1.3187],
        [ 0.8093,  1.6915,  0.2524],
        [ 0.3587, -0.3087,  0.4253],
        [-0.2142, -1.0672, -0.3767],
        [ 0.2627, -0.1250,  0.6398]])


In [10]:
print(x.size())

torch.Size([5, 3])


In [11]:
y = torch.rand(5,3)
print(x)

tensor([[ 0.5203,  0.4406, -1.3187],
        [ 0.8093,  1.6915,  0.2524],
        [ 0.3587, -0.3087,  0.4253],
        [-0.2142, -1.0672, -0.3767],
        [ 0.2627, -0.1250,  0.6398]])


In [12]:
print(x+y)     #  print(torch.add(x+y))

tensor([[ 1.1027,  1.3366, -0.9305],
        [ 1.3422,  2.1511,  0.9309],
        [ 0.6979,  0.5797,  1.0829],
        [-0.1669, -0.5749, -0.1771],
        [ 0.8363,  0.4596,  1.0579]])


In [14]:
result = torch.empty(5,3)
torch.add(5,3,out=result)
print(result)

tensor(8.)


In [15]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.1027,  1.3366, -0.9305],
        [ 1.3422,  2.1511,  0.9309],
        [ 0.6979,  0.5797,  1.0829],
        [-0.1669, -0.5749, -0.1771],
        [ 0.8363,  0.4596,  1.0579]])


In [16]:
x = torch.randn(4, 4)
print(x)
y = x.view(16)
print(y)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(z)
print(x.size(), y.size(), z.size())

tensor([[ 0.3772,  1.4799, -0.6033,  0.8764],
        [-2.2298, -0.7859,  1.4260, -0.9443],
        [-1.3802,  1.4097, -1.1398, -1.8639],
        [ 1.0936,  1.2126,  0.0773, -0.0454]])
tensor([ 0.3772,  1.4799, -0.6033,  0.8764, -2.2298, -0.7859,  1.4260, -0.9443,
        -1.3802,  1.4097, -1.1398, -1.8639,  1.0936,  1.2126,  0.0773, -0.0454])
tensor([[ 0.3772,  1.4799, -0.6033,  0.8764, -2.2298, -0.7859,  1.4260, -0.9443],
        [-1.3802,  1.4097, -1.1398, -1.8639,  1.0936,  1.2126,  0.0773, -0.0454]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [17]:
#If you have a one element tensor, use .item() to get the value as a Python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.7759])
-0.7758641839027405


In [18]:
a = torch.ones(5,dtype=torch.int)
print(a)

tensor([1, 1, 1, 1, 1], dtype=torch.int32)


In [19]:
b = a.numpy()
print(b)

[1 1 1 1 1]


In [20]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [0]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
